spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mariadb://localhost:3306/four_weekdays3
    username: ${LOCAL_DB_USERNAME:root}
    password: ${LOCAL_DB_PASSWORD:qwer1234}

cookie:
  secure: false
